# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_curso_alumnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='alumnos',
            field=models.ManyToManyField(blank=True, default='', to='myapp.Alumno'),
        ),
    ]
